'use strict';

const Promise = require('bluebird');
const knex = require('./knex');

function BandMessages() {
    return knex('band_messages');
}

function VenueMessages() {
    return knex('venue_messages');
}



function createAutogenerated(origin, message) {
    return new Promise(function(resolve, reject) {
        switch (origin) {
            case 'bands':
                BandMessages()
                    .insert(message)
                    .then(function(msg) {
                        resolve(msg[0]);
                    }).catch(reject);
                break;
            case 'venues':
                VenueMessages()
                    .insert(message)
                    .then(function(msg) {
                        resolve(msg[0]);
                    }).catch(reject);
                break;
            default: reject({
                err: "Invalid origin type: " + origin
            });
        }
    });
}



module.exports = {
    createAutogenerated: createAutogenerated
};
